### ISSUE TITLE
Can't import package due to error

### ISSUE THREAD

**Issue by sbezboro** [TeamSirenix/odin-serializer#36]
When I try to import the downloaded package from the odin serializer site, I get this error:

`Failed to import package with error: Couldn't decompress package`

Tried searching but couldn't find anything conclusive. I'm using the absolute latest version of Unity at the time of this writing (2019.3.0f1), maybe that's the reason

**Comment by SugoiDev** [comment]
Are you on a Mac?
I think that's a known issue on Mac due to how the package is being compressed and the fact that Mac uses BSD Tar instead of GNU tar.

They're looking into fixing it.
In the meantime, you could try this one I just exported myself from the latest version (2019.12.13 - 07e24d68).

[odinserializer 2019.12.13 - 07e24d68.unitypackage.zip](https://github.com/TeamSirenix/odin-serializer/files/3990598/odinserializer.2019.12.13.-.07e24d68.unitypackage.zip)

**Comment by sbezboro** [comment]
Ah yes, I'm using a Mac. Thanks for providing a workaround.

How do I use this file? Not sure how to use the extracted contents, and if I drop the .zip from the name and try importing it, Unity says there are no new assets to import, even though I definitely don't have Odin Serializer in my project yet.

**Comment by SugoiDev** [comment]
Unzip the file, then import the Unity package in Unity as normal.
Github didn't let me upload the .Unitypackage direclty, so I zipped it.

I just uploaded the .unitypackage to my dropbox. You can download it from this link: [odinserializer 2019.12.13 - 07e24d68.unitypackage](https://www.dropbox.com/s/8irncmqenn3ehvp/odinserializer%202019.12.13%20-%2007e24d68.unitypackage?dl=0)

**Comment by sbezboro** [comment]
Ah that direct link worked, thanks! Not sure what was happening with the zip, it wasn't extracting properly for some reason.

**Comment by TorVestergaard** [comment]
Since it's still an issue we should fix, I'll leave this open until we do :)

**Comment by TorVestergaard** [comment]
Alright, this issue should be officially resolved - now we package the file in a slightly different way that seems to work for Unity on both Windows and Mac.
