### ISSUE TITLE
Should Guid's be serialized as strings?

### ISSUE THREAD

**Issue by ccfoo242** [TeamSirenix/odin-serializer#52]
Hey there, I noticed that a guid I have in my serialized object causes several editors (VS 2022, VS Code, Notepad++) to whine about an invalid character sequence.
![image](https://user-images.githubusercontent.com/6061719/171024291-0e59500c-b8f3-421e-ac91-14248dcf7169.png)

Is there an option somewhere to force it to quote the guid value or serialize as string by default?

Note, I have no problem deserializing these with odin, but I plan to post this to an aspnet core api and I'm not sure yet if that will be able to parse a guid like this. 
[edit - as a workaround i can just use string in my class and use guid.ToString() when creating it]

**Comment by TorVestergaard** [comment]
This is intentional, and not the only case where such warnings would be generated (for example, external and internal graph references also do so). Odin Serializer does not produce entirely up-to-spec json, as there is no true interoperability with other json serializers anyways due to the heavy metadata annotations the serializer adds and requires. It is meant primarily to serve as a human-readable format.

**Comment by ccfoo242** [comment]
Ok, thanks for the info!
