### ISSUE TITLE
Is anyone maintaining this repo? Or should we switch serializers and out of Odin?

### ISSUE THREAD

**Issue by pshtif** [TeamSirenix/odin-serializer#61]
It seems that there are fixes which are part of Odin Serializer that is inside Odin package but they are not published here. Does it mean to get the latest serializer you need to grab a license of the official Odin and use that? 

Even downloading latest Odin Serializer from https://odininspector.com/download is the old version not including latest 2022 fixes for example.

**Comment by TorVestergaard** [comment]
This repo is being maintained - though there's been a period where I've not been pushing new fixes here. Changes to improve our internal workflow made it challenging to move commits into the open source repo, but they should be resolved now.

This question had good timing - it was literally yesterday that I finally finished work on that (been ongoing for a little bit) and rebased every commit since May 2023 into this repo. Changes should arrive more promptly from Odin Inspector's internal version (where most of our work generally happens) now, as they used to before.

I apologize for letting things get so out of date - we've been quite busy!
